codecov:
  require_ci_to_pass: true
  require_changes: false

coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default