codecov:
  require_ci_to_pass: true

coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false