spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:19093}



security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:money-town-user-service}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30m}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:14d}
