spring:
  application:
    name: settlement-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:19093}

settlement:
  scheduler:
    revenue-polling:
      enabled: ${SETTLEMENT_REVENUE_POLLING_ENABLED:true}