server:
  port: 19098

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/analysis_db}

fds:
  rules:
    RAPID_REQUEST:
      window-seconds: 1
      normal: 5
      suspicious: 3
    BURST_REQUEST:
      window-seconds: 10
      normal: 20
      suspicious: 10
    MULTI_OFFERING_BURST:
      window-seconds: 10
      normal: 5
      suspicious: 3



notification:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}