server:
  port: 19096

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/offering_db}

  cloud:
    openfeign:
      client:
        config:
          user-service:
            connect-timeout: ${USER_SERVICE_CONNECT_TIMEOUT:1000}
            read-timeout: ${USER_SERVICE_READ_TIMEOUT:2000}

          analysis-service:
            connect-timeout: ${ANALYSIS_SERVICE_CONNECT_TIMEOUT:1000}
            read-timeout: ${ANALYSIS_SERVICE_READ_TIMEOUT:2000}

          asset-service:
            connect-timeout: ${ASSET_SERVICE_CONNECT_TIMEOUT:1000}
            read-timeout: ${ASSET_SERVICE_READ_TIMEOUT:2000}

subscription:
  reservation-timeout-minutes: ${SUBSCRIPTION_RESERVATION_TIMEOUT_MINUTES:10}