
bootJar {
    enabled = false
}
jar {
    enabled = true
    archiveClassifier = ''
}

dependencies {
    compileOnly 'org.springframework:spring-web'
    compileOnly 'org.springframework:spring-webmvc'

    // 테스트
    testImplementation 'org.springframework:spring-web'
    testImplementation 'org.springframework.data:spring-data-jpa'

    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly 'com.fasterxml.jackson.core:jackson-annotations'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    compileOnly 'jakarta.validation:jakarta.validation-api'
    compileOnly 'org.springframework.data:spring-data-jpa'
    compileOnly 'io.github.openfeign:feign-core'
    compileOnly 'org.slf4j:slf4j-api'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly "com.querydsl:querydsl-jpa:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"

    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
}